### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by steveassassin66** [Funwayguy/StandardQuestingPack#13]
---- Minecraft Crash Report ----
// Sorry :(

Time: 5/30/16 3:34 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: codechicken/nei/recipe/ICraftingHandler
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: codechicken/nei/recipe/ICraftingHandler
    at tonius.neiintegration.NEIIntegration.init(NEIIntegration.java:45)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: codechicken.nei.recipe.ICraftingHandler
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 37 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 121111600 bytes (115 MB) / 340058112 bytes (324 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 Optifine OptiFine_1.7.10_HD_U_D4 24 mods loaded, 24 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHI    FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1481-1.7.10.jar) 
    UCHI    Forge{10.13.4.1481} [Minecraft Forge](forge-1.7.10-10.13.4.1481-1.7.10.jar) 
    UCHI    appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHI    mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting](minecraft.jar) 
    UCHI    FastCraft{1.23} [FastCraft](fastcraft-1.23.jar) 
    UCHI    gilded-games-util{1.7.10-1.1} [Gilded Games Utility](gilded-games-util.jar) 
    UCHI    bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) 
    UCHI    Treecapitator{1.7.10} [Treecapitator]([1.7.10]Treecapitator-universal-2.0.4.jar) 
    UCHE    aether{Alpha 1.7.10-1.3} [Aether II](aether.jar) 
    UCHI    appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCHI    Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) 
    UCHI    DamageIndicatorsMod{3.2.0} [Damage Indicators](Damage-Indicators-Mod-1.7.10.jar) 
    UCHI    endercore{1.7.10-0.2.0.35_beta} [EnderCore](EnderCore-1.7.10-0.2.0.35_beta.jar) 
    UCHI    EnderIO{1.7.10-2.3.0.426_beta} [Ender IO](Ender-IO-Mod-1.7.10.jar) 
    UCHI    InventoryPets{1.4.3} [Inventory Pets](inventorypets-1.7.10-1.4.3-universal.jar) 
    UCHI    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCHI    Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCHI    MoreFurnaces{1.3.9} [More Furnaces](MoreFurnaces-1.3.9-MC1.7.10.jar) 
    UCHI    cfm{3.4.7} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.7%281.7.10%29.jar) 
    UCHE    neiintegration{1.0.5} [NEI Integration](NEIIntegration-MC1.7.10-1.0.5.jar) 
    UCHI    harvestcraft{1.7.10g} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10h.jar) 
    UCHI    Roguelike{1.4.4} [Roguelike Dungeons](roguelike-1.7.10-1.4.4.jar) 
    UCHI    TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics'
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    TConstruct Environment: Environment healthy.
    EnderIO: Found the following problem(s) with your installation:
                  \* Optifine is installed. This is NOT supported.
                  \* Our API got loaded from Ender-IO-Mod-1.7.10.jar. That's unexpected.
                  \* Our API got loaded from Ender-IO-Mod-1.7.10.jar. That's unexpected.
                  \* Our API got loaded from Ender-IO-Mod-1.7.10.jar. That's unexpected.
                  \* Our API got loaded from Ender-IO-Mod-1.7.10.jar. That's unexpected.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
    OptiFine Version: OptiFine_1.7.10_HD_U_D4
    Render Distance Chunks: 2
    Mipmaps: 4
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    OpenGlVersion: 3.1.0 - Build 9.17.10.4229
    OpenGlRenderer: Intel(R) HD Graphics
    OpenGlVendor: Intel
    CpuCount: 2

**Comment by Funwayguy** [comment]
This crash report isn't BetterQuesting or StandardExpansion related. This happened because you have NEI Integration without even having NEI installed.
