### ISSUE TITLE
Cant log in to 1.10.2 server

### ISSUE THREAD

**Issue by APolarBaer** [Funwayguy/StandardQuestingPack#28]
[14:03:06] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:58134
java.lang.NullPointerException
        at bq_standard.rewards.loot.LootRegistry.sendDatabase(LootRegistry.java:126) ~[LootRegistry.class:?]
        at bq_standard.rewards.loot.LootRegistry.onPlayerJoin(LootRegistry.java:224) ~[LootRegistry.class:?]

Edit:

Girth: http://pastebin.com/C020hYtU

**Comment by APolarBaer** [comment]
removed standard questing pack from server, is it client side only?

**Comment by Funwayguy** [comment]
Crashlog is missing mod version and Minecraft version info.

**Comment by APolarBaer** [comment]
1.10.2 
2.3.110

**Comment by Funwayguy** [comment]
2.3.110 of what? BetterQuesting or StandardExpansion (I'd still need to know both)

**Comment by APolarBaer** [comment]
Better questing is 1.3.180
Standard expansion is 2.3.110
Mc is 1.10.2
Forge is 12.18.3.2185

**Comment by Funwayguy** [comment]
You can't use a 1.x.x (BQ1) base mod with 2.x.x (BQ2) expansions.

**Comment by APolarBaer** [comment]
Then where do I get bq2 base....
